name: 'NPM Publish'
description: 'Publish a package to NPM'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  registry:
    description: 'The registry to publish to'
    required: true
  access:
    description: 'Whether the package is public or private'
    required: false
    default: 'private'
